### ISSUE TITLE
Allow users to configure additional context to be sent to the AI

### ISSUE THREAD

**Issue by scastlara** [elementsinteractive/lgtm-ai#25]
Something like that would allow users to pass in additional stuff that they deem important.
Think of some other improvements, for instance:

```toml
[[additional-context]]
file-path = "docs/development-guidelines.md"
prompt = "These are the teams' development guidelines, take them into consideration when reviewing the PR."

[[additional-context]]
file-path = "pyproject.toml"
prompt = "This is the project config file, ignore all errors that would be otherwise catched by our linting tools configured there."
```

This is just an example, to give whoever picks this up inspiration.
